#!/usr/bin/env php
<?php

if (!$loader = include __DIR__ . '/../vendor/autoload.php') {
    die('You must set up the project dependencies.');
}

/** @var \Cilex\Application $app */
$app = require 'bootstrap.php';

$app->run();
